React Capstone Project
taldr27/Stock-Prices pull request #7
Opened 2022-11-29 22:29 UTC by taldr27

# Stock Prices Project
In this project I:
Please I only have these limited calls remaining, to update the API key I have to create another email.
![image](https://user-images.githubusercontent.com/107952724/204662359-6af47b48-07f7-44ef-b0af-3c1e7f11da5f.png)

- Used React documentation.
- Used React components.
- Used API to fetch data from [financial modeling](https://site.financialmodelingprep.com/developer/docs/dashboard/)
- Used React props.
- Used React Router.
- Connected React and Redux.
- Handled events in a React app.
- Used styles in a React app.
- Applied React best practices and language style guides in code.
- Used store, actions, and reducers in React.
- Performed a code review between team members.
- Wrote unit tests with React Testing Library.
![image](https://user-images.githubusercontent.com/107952724/204662129-318ad6a0-c79f-4d74-aa90-17181251e652.png)

## [Live Page](https://deploy-preview-38--singular-maamoul-ab8f49.netlify.app/)

2022-11-29 23:08 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @taldr27,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍
✅ Linter checks passed 👍
✅ Good commit messages 👍 
✅ App is a SPA 👍
✅ Used Redux well 👍
✅ All pages work fine as expected 👍
✅ App is hosted and works fine both locally and hosted link 👍 
✅ Tests passed 👍

## Required Changes ♻️
_Check the comments under the review._

A good job is done so far on your project. Considering the hard work done on this project, it will be a great idea to have a video presentation to sell your skills to a potential employer and hence:
- [ ] You are required to have a demo presentation video of yourself presenting the project's objectives, features, live demo, and also a code section you are most proud of implementing in this project. Kindly add a video presentation. Loom is recommended to do the video with 5 minutes max.

**Project requirement**
![image](https://user-images.githubusercontent.com/50941074/204669567-31c81573-a682-4394-b890-f7c645a5f4a4.png)

- [ ] Kindly take notes of the points in the screenshot below:

![image](https://user-images.githubusercontent.com/50941074/204667580-487ab236-6d02-4e9a-9f4a-edc10020e640.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-11-29 23:08 UTC, AmaduKamara commented on README.md
> +
- [x] This command `npm run` gives other options as to what the viewer of the project wants. It would be nice if you could complete the command to `npm run start` as that's the main command used to run or start the app. Kindly modify that 👍

2022-11-29 23:08 UTC, AmaduKamara commented on README.md
> +## 📝 License <a name="license"></a>
- [x] Either below or above these headings, you are required to add an acknowledgment to the original creator of the design used as inspiration for this capstone project. Please give credit to Nelson Sakwa for the great work done. 👍 

![image](https://user-images.githubusercontent.com/50941074/204666450-450075cc-c6f1-4a7a-b9eb-a9f70fc7555d.png)

2022-11-29 23:16 UTC, taldr27 commented on README.md
> +## 📝 License <a name="license"></a>
@AmaduKamara Hello, thanks for your review, you are not able to see my video?

2022-11-29 23:41 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @taldr27, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [x] As suggested by the previous reviewer, Kindly add in the video presentation highlighting the code section you are most proud of implementing in this project. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 00:31 UTC, Reem-lab approved these changes
# Hi Team, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- No Linters error ✅
- Followed Gitflow ✅
- Great working on the functionality and design🔥🚀🎉
- Well Deployed projects ✅
- Good presentation video ✅
- Professional ReadME file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 06:41 UTC, merged